SYMBOLS = [
    { "symbol": "A1CAP", "name": "A1 Capital", "category": "BIST100" },
    { "symbol": "ACSEL", "name": "Acıselsan Acıpayam Selüloz", "category": "BIST100" },
    { "symbol": 'ADEL', "name": 'Adel Kalemcilik', "category": 'BIST100' },
    { "symbol": 'ADESE', "name": 'Adese AVM', "category": 'BIST100' },
    { "symbol": 'ADGYO', "name": 'Adra GYO', "category": 'BIST100' },
    { "symbol": 'AEFES', "name": 'Anadolu Efes', "category": 'BIST100' },
    { "symbol": 'AFYON', "name": 'Afyon Çimento', "category": 'BIST100' },
    { "symbol": 'AGESA', "name": 'Agesa Hayat ve Emeklilik', "category": 'BIST100'},
    { "symbol": 'AGHOL', "name": 'Anadolu Grubu Holding', "category": 'BIST100' },
    { "symbol": 'AGROT', "name": 'Agrotech Yüksek Teknoloji', "category": 'BIST100' },
    { "symbol": 'AGYO', "name": 'Atakule GYO', "category": 'BIST100' },
    { "symbol": 'AHGAZ', "name": 'Ahlatcı Doğalgaz', "category": 'BIST100' },
    { "symbol": 'AHSGY', "name": 'Ahes GYO', "category": 'BIST100' },
    { "symbol": 'AKBNK', "name": 'Akbank', "category": 'BIST100' },
    { "symbol": 'AKCNS', "name": 'Akçansa', "category": 'BIST100' },
    { "symbol": 'AKENR', "name": 'Akenerji', "category": 'BIST100' },
    { "symbol": 'AKFGY', "name": 'Akfen GYO', "category": 'BIST100' },
    { "symbol": 'AKFIS', "name": 'Akfen İnşaat', "category": 'BIST100' },
    { "symbol": 'AKFYE', "name": 'Akfen Yenilenebilir Enerji', "category": 'BIST100' },
    { "symbol": 'AKGRT', "name": 'Aksigorta', "category": 'BIST100' },
    { "symbol": 'AKMGY', "name": 'Akmerkez GYO', "category": 'BIST100' },
    { "symbol": 'AKSA', "name": 'Aksa', "category": 'BIST100' },
    { "symbol": 'AKSEN', "name": 'Aksa Enerji', "category": 'BIST100' },
    { "symbol": 'AKSGY', "name": 'Akis GYO', "category": 'BIST100' },
    { "symbol": 'AKSUE', "name": 'Aksu Enerji', "category": 'BIST100' },
    { "symbol": 'AKYHO', "name": 'Akdeniz Yatırım Holding', "category": 'BIST100' },
    { "symbol": 'ALARK', "name": 'Alarko Holding', "category": 'BIST100' },
    { "symbol": 'ALBRK', "name": 'Albaraka Türk', "category": 'BIST100' },
    { "symbol": 'ALCAR', "name": 'Alarko Carrier', "category": 'BIST100' },
    { "symbol": 'ALCTL', "name": 'Alcatel Teletaş', "category": 'BIST100' },
    { "symbol": 'ALFAS', "name": 'Alfa Solar', "category": 'BIST100' },
    { "symbol": 'ALGYO', "name": 'Alarko GYO', "category": 'BIST100' },
    { "symbol": 'ALKA', "name": 'Alkim Kağıt', "category": 'BIST100' },
    { "symbol": 'ALKIM', "name": 'Alkim', "category": 'BIST100' },
    { "symbol": 'ALKLC', "name": 'Altınkılıç Gıda', "category": 'BIST100' },
    { "symbol": 'RUZYE', "name": 'RUZY MADENCILIK VE ENERJI', "category": 'BIST100' },
    { "symbol": 'ALTNY', "name": 'Altınay Savunma', "category": 'BIST100' },
    { "symbol": 'ALVES', "name": 'Alves Kablo', "category": 'BIST100' },
    { "symbol": 'ANELE', "name": 'Anel Elektrik', "category": 'BIST100' },
    { "symbol": 'ANGEN', "name": 'Anatolia Biyoteknoloji', "category": 'BIST100' },
    { "symbol": 'ANHYT', "name": 'Anadolu Hayat Emeklilik A.Ş.', "category": 'BIST100' },
    { "symbol": 'ANSGR', "name": 'Anadolu Sigorta', "category": 'BIST100' },
    { "symbol": 'ARASE', "name": 'Doğu Aras Enerji', "category": 'BIST100' },
    { "symbol": 'ARCLK', "name": 'Arçelik', "category": 'BIST100' },
    { "symbol": 'ARDYZ', "name": 'ARD Grup Bilişim', "category": 'BIST100' },
    { "symbol": 'ARENA', "name": 'Arena Bilgisayar', "category": 'BIST100' },
    { "symbol": 'ARMGD', "name": 'Armada Gıda', "category": 'BIST100' },
    { "symbol": 'ARSAN', "name": 'Arsan Tekstil', "category": 'BIST100' },
    { "symbol": 'ARTMS', "name": 'Artemis Halı', "category": 'BIST100' },
    { "symbol": 'ARZUM', "name": 'Arzum Ev Aletleri', "category": 'BIST100' },
    { "symbol": 'ASELS', "name": 'Aselsan', "category": 'BIST100' },
    { "symbol": 'ASGYO', "name": 'Asce GYO', "category": 'BIST100' },
    { "symbol": 'ASTOR', "name": 'Astor Enerji', "category": 'BIST100' },
    { "symbol": 'ASUZU', "name": 'Anadolu İsuzu', "category": 'BIST100' },
    { "symbol": 'ATAGY', "name": 'Ata GYO', "category": 'BIST100' },
    { "symbol": 'ATAKP', "name": 'Atakey Patates', "category": 'BIST100' },
    { "symbol": 'ATATP', "name": 'ATP Bilgisayar', "category": 'BIST100' },
    { "symbol": 'ATEKS', "name": 'Akın Tekstil', "category": 'BIST100' },
    { "symbol": 'ATLAS', "name": 'Atlas YO', "category": 'BIST100' },
    { "symbol": 'ATSYH', "name": 'Atlantis YO', "category": 'BIST100' },
    { "symbol": 'AVGYO', "name": 'Avrasya YO', "category": 'BIST100' },
    { "symbol": 'AVHOL', "name": 'Avrupa Yatırım Holding', "category": 'BIST100' },
    { "symbol": 'AVOD', "name": 'AVOD Kurutulmuş Gıda', "category": 'BIST100' },
    { "symbol": 'AVPGY', "name": 'Avrupakent GYO', "category": 'BIST100' },
    { "symbol": 'AVTUR', "name": 'Avrasya Petrol&Turistik Tesis', "category": 'BIST100' },
    { "symbol": 'AYCES', "name": 'Altınyunus Çeşme', "category": 'BIST100' },
    { "symbol": 'AYDEM', "name": 'Aydem Enerji', "category": 'BIST100' },
    { "symbol": 'AYEN', "name": 'Ayen Enerji', "category": 'BIST100' },
    { "symbol": 'AYES', "name": 'Ayes Çelik Hasır & Çit', "category": 'BIST100' },
    { "symbol": 'AYGAZ', "name": 'Aygaz', "category": 'BIST100' },
    { "symbol": 'AZTEK', "name": 'Aztek Teknoloji', "category": 'BIST100' },
    { "symbol": 'BAGFS', "name": 'Bandırma Gübre Fabrikaları A.Ş', "category": 'BIST100' },
    { "symbol": 'BAHKM', "name": 'Bahdır Kimya', "category": 'BIST100' },
    { "symbol": 'BAKAB', "name": 'Bak Ambalaj', "category": 'BIST100' },
    { "symbol": 'BALAT', "name": 'Balatacılar Balatacılık', "category": 'BIST100' },
    { "symbol": 'BANVT', "name": 'Banvit', "category": 'BIST100' },
    { "symbol": 'BASCM', "name": 'Baştaş Başkent Çimento Sanayi', "category": 'BIST100' },
    { "symbol": 'BASGZ', "name": 'Başkent Doğalgaz', "category": 'BIST100' },
    { "symbol": 'BAYRK', "name": 'Bayrak EBT Taban', "category": 'BIST100' },
    { "symbol": 'BEGYO', "name": 'Batı Ege GYO', "category": 'BIST100' },
    { "symbol": 'BERA', "name": 'Bera Holding', "category": 'BIST100' },
    { "symbol": 'BEYAZ', "name": 'Beyaz Filo', "category": 'BIST100' },
    { "symbol": 'BFREN', "name": 'Bosch Fren', "category": 'BIST100' },
    { "symbol": 'BIENY', "name": 'Bien Yapı', "category": 'BIST100' },
    { "symbol": 'BIMAS', "name": 'Bim Birleşik Mağazalar A.Ş', "category": 'BIST100' },
    { "symbol": 'BINBN', "name": 'BinBin', "category": 'BIST100' },
    { "symbol": 'BINHO', "name": '1000 Yatırımlar', "category": 'BIST100' },
    { "symbol": 'BIOEN', "name": 'Biotrend Enerji', "category": 'BIST100' },
    { "symbol": 'BIZIM', "name": 'Bizim Toptan', "category": 'BIST100' },
    { "symbol": 'BJKAS', "name": 'Beşiktaş', "category": 'BIST100' },
    { "symbol": 'BLCYT', "name": 'Bilici Yatırım', "category": 'BIST100' },
    { "symbol": 'BMSCH', "name": 'BMS Çelik Hasır', "category": 'BIST100' },
    { "symbol": 'BMSTL', "name": 'BMS Birleşik Metal', "category": 'BIST100' },
    { "symbol": 'BNTAS', "name": 'Bantaş Bandırma Ambalaj', "category": 'BIST100' },
    { "symbol": 'BOBET', "name": 'Boğaziçi Beton', "category": 'BIST100' },
    { "symbol": 'BORLS', "name": 'Borlease Otomativ', "category": 'BIST100' },
    { "symbol": 'BORSK', "name": 'Bor Şeker', "category": 'BIST100' },
    { "symbol": 'BOSSA', "name": 'Bossa', "category": 'BIST100' },
    { "symbol": 'BRISA', "name": 'Brisa', "category": 'BIST100' },
    { "symbol": 'BRKO', "name": 'Birko Mensucat', "category": 'BIST100' },
    { "symbol": 'BRKSN', "name": 'Berkosan Yatırım', "category": 'BIST100' },
    { "symbol": 'BRKVY', "name": 'Birikim Varlık', "category": 'BIST100' },
    { "symbol": 'BRLSM', "name": 'Birleşim Mühendislik', "category": 'BIST100' },
    { "symbol": 'BRMEN', "name": 'Birlik Mensucat', "category": 'BIST100' },
    { "symbol": 'BRSAN', "name": 'Borusan Birleşik Boru Fab.', "category": 'BIST100' },
    { "symbol": 'BRYAT', "name": 'Borusan Yatırım', "category": 'BIST100' },
    { "symbol": 'BSOKE', "name": 'Batı Söke Çimento', "category": 'BIST100' },
    { "symbol": 'BTCIM', "name": 'Batıçim', "category": 'BIST100' },
    { "symbol": 'BUCIM', "name": 'Bursa Çimento', "category": 'BIST100' },
    { "symbol": 'BURCE', "name": 'Burçelik', "category": 'BIST100' },
    { "symbol": 'BURVA', "name": 'Burçelik Vana Sanayii', "category": 'BIST100' },
    { "symbol": 'BVSAN', "name": 'Bülbüloğlu Vinç', "category": 'BIST100' },
    { "symbol": 'BYDNR', "name": 'Baydöner', "category": 'BIST100' },
    { "symbol": 'CANTE', "name": 'Çan2 Termik A.Ş', "category": 'BIST100' },
    { "symbol": 'CASA', "name": 'Casa Emtia Pertol Kim.Tür.AŞ', "category": 'BIST100' },
    { "symbol": 'CATES', "name": 'Çates Elektrik', "category": 'BIST100' },
    { "symbol": 'CCOLA', "name": 'Coca Cola İçecek A.Ş', "category": 'BIST100' },
    { "symbol": 'CELHA', "name": 'Çelik Halat', "category": 'BIST100' },
    { "symbol": 'CEMAS', "name": 'Çemas Döküm', "category": 'BIST100' },
    { "symbol": 'CEMTS', "name": 'Çemtaş', "category": 'BIST100' },
    { "symbol": 'CEMZY', "name": 'Cem Zeytin', "category": 'BIST100' },
    { "symbol": 'CEOEM', "name": 'CEO Event Medya', "category": 'BIST100' },
    { "symbol": 'CGCAM', "name": 'Çağdaş Cam', "category": 'BIST100' },
    { "symbol": 'CIMSA', "name": 'Çimsa', "category": 'BIST100' },
    { "symbol": 'CLEBI', "name": 'Çelebi', "category": 'BIST100' },
    { "symbol": 'CMBTN', "name": 'Çimbeton', "category": 'BIST100' },
    { "symbol": 'CMENT', "name": 'Çimentaş', "category": 'BIST100' },
    { "symbol": 'CONSE', "name": 'Consus Enerji', "category": 'BIST100' },
    { "symbol": 'COSMO', "name": 'Cks ks Yatırım Holding', "category": 'BIST100' },
    { "symbol": 'CRDFA', "name": 'Creditwest Faktoring', "category": 'BIST100' },
    { "symbol": 'CRFSA', "name": 'Carrefoursa', "category": 'BIST100' },
    { "symbol": 'CUSAN', "name": 'Çuhadaroğlu Metal', "category": 'BIST100' },
    { "symbol": 'CVKMD', "name": 'Cvk Maden', "category": 'BIST100' },
    { "symbol": 'CWENE', "name": 'Cw Enerji', "category": 'BIST100' },
    { "symbol": 'DAGHL', "name": 'Dagi Yatırım Holding A.Ş', "category": 'BIST100' },
    { "symbol": 'DAGI', "name": 'Dagi Giyim', "category": 'BIST100' },
    { "symbol": 'DAPGM', "name": 'Dap Gayrimenkul', "category": 'BIST100' },
    { "symbol": 'DARDL', "name": 'Dardanel', "category": 'BIST100' },
    { "symbol": 'DCTTR', "name": 'Dct Trading', "category": 'BIST100' },
    { "symbol": 'DENGE', "name": 'Denge Holding', "category": 'BIST100' },
    { "symbol": 'DERHL', "name": 'Derlüks Yatırım Holding', "category": 'BIST100' },
    { "symbol": 'DERIM', "name": 'Derimod', "category": 'BIST100' },
    { "symbol": 'DESA', "name": 'Desa Deri Sanayii', "category": 'BIST100' },
    { "symbol": 'DESPC', "name": 'Despec Bilgisayar', "category": 'BIST100' },
    { "symbol": 'DEVA', "name": 'Deva Holding', "category": 'BIST100' },
    { "symbol": 'DGATE', "name": 'Datagate', "category": 'BIST100' },
    { "symbol": 'DGGYO', "name": 'Doğuş GE GYO', "category": 'BIST100' },
    { "symbol": 'DGNMO', "name": 'Doğanlar Mobilya', "category": 'BIST100' },
    { "symbol": 'DIRIT', "name": 'Diriteks Diriliş Tekstil', "category": 'BIST100' },
    { "symbol": 'DITAS', "name": 'Ditaş Doğan', "category": 'BIST100' },
    { "symbol": 'DMRGD', "name": 'DMR Unlu Mamüller', "category": 'BIST100' },
    { "symbol": 'DMSAS', "name": 'Demisaş', "category": 'BIST100' },
    { "symbol": 'DNISI', "name": 'Dinamik Isı Yalıtım', "category": 'BIST100' },
    { "symbol": 'DOAS', "name": 'Doğuş Otomativ', "category": 'BIST100' },
    { "symbol": 'DOBUR', "name": 'Doğan Burda', "category": 'BIST100' },
    { "symbol": 'DOCO', "name": 'DO & CO Aktiengesellscahft', "category": 'BIST100' },
    { "symbol": 'DOFER', "name": 'Dofer Yapı', "category": 'BIST100' },
    { "symbol": 'DOGUB', "name": 'Doğusan', "category": 'BIST100' },
    { "symbol": 'DOHOL', "name": 'Doğan Holding', "category": 'BIST100' },
    { "symbol": 'DOKTA', "name": 'Döktaş Dökümcülük', "category": 'BIST100' },
    { "symbol": 'DSTKF', "name": 'Destek Finans Faktoring', "category": 'BIST100' },
    { "symbol": 'DURDO', "name": 'Duran Ofset', "category": 'BIST100' },
    { "symbol": 'DURKN', "name": 'Durukan Şekerleme', "category": 'BIST100' },
    { "symbol": 'DYOBY', "name": 'DYO Boya', "category": 'BIST100' },
    { "symbol": 'DZGYO', "name": 'Deniz GYO', "category": 'BIST100' },
    { "symbol": 'EBEBK', "name": 'Ebebek', "category": 'BIST100' },
    { "symbol": 'ECILC', "name": 'Eczacıbaşı İlaç', "category": 'BIST100' },
    { "symbol": 'ECZYT', "name": 'Eczacıbaşı Yatırım', "category": 'BIST100' },
    { "symbol": 'EDATA', "name": 'E-Data Teknoloji', "category": 'BIST100' },
    { "symbol": 'EDIP', "name": 'Edip Gayrimenkul Yat. San.', "category": 'BIST100' },
    { "symbol": 'EFORC', "name": 'Efor Çay', "category": 'BIST100' },
    { "symbol": 'EGEEN', "name": 'Ege Endüstri', "category": 'BIST100' },
    { "symbol": 'EGEGY', "name": 'Egeyapı GYO', "category": 'BIST100' },
    { "symbol": 'EGEPO', "name": 'Egepol Hastanesi', "category": 'BIST100' },
    { "symbol": 'EGGUB', "name": 'Ege Gübre', "category": 'BIST100' },
    { "symbol": 'EGPRO', "name": 'Ege Profil', "category": 'BIST100' },
    { "symbol": 'EGSER', "name": 'Ege Seramik', "category": 'BIST100' },
    { "symbol": 'EKGYO', "name": 'Emlak Konut GYO', "category": 'BIST100' },
    { "symbol": 'EKIZ', "name": 'Ekiz Yağ ve Sabun', "category": 'BIST100' },
    { "symbol": 'EKOS', "name": 'Ekos Teknoloji', "category": 'BIST100' },
    { "symbol": 'EKSUN', "name": 'Eksun Gıda', "category": 'BIST100' },
    { "symbol": 'ELITE', "name": 'Elite Organik Gıda', "category": 'BIST100' },
    { "symbol": 'EMKEL', "name": 'Emek Elektrik', "category": 'BIST100' },
    { "symbol": 'EMNIS', "name": 'Eminiş Ambalaj', "category": 'BIST100' },
    { "symbol": 'ENDAE', "name": 'Enda Enerji', "category": 'BIST100' },
    { "symbol": 'ENERY', "name": 'Enerya Enerji', "category": 'BIST100' },
    { "symbol": 'ENJSA', "name": 'Enerjisa Enerji', "category": 'BIST100' },
    { "symbol": 'ENKAI', "name": 'Enka İnşaat', "category": 'BIST100' },
    { "symbol": 'ENSRI', "name": 'Ensari Deri', "category": 'BIST100' },
    { "symbol": 'ENTRA', "name": 'Ic Enterra Yenilenebilir', "category": 'BIST100' },
    { "symbol": 'EPLAS', "name": 'Egeplast', "category": 'BIST100' },
    { "symbol": 'ERBOS', "name": 'Erbosan', "category": 'BIST100' },
    { "symbol": 'ERCB', "name": 'Erciyes Çelik Boru', "category": 'BIST100' },
    { "symbol": 'EREGL', "name": 'Ereğli Demir Çelik', "category": 'BIST100' },
    { "symbol": 'ERSU', "name": 'Ersu Gıda', "category": 'BIST100' },
    { "symbol": 'ESCAR', "name": 'Escar Filo', "category": 'BIST100' },
    { "symbol": 'ESCOM', "name": 'Escort Computer', "category": 'BIST100' },
    { "symbol": 'ESEN', "name": 'Esenboğa Elektrik', "category": 'BIST100' },
    { "symbol": 'ETILR', "name": 'Etiler Gıda', "category": 'BIST100' },
    { "symbol": 'ETYAT', "name": 'Euro Trend Yatırım', "category": 'BIST100' },
    { "symbol": 'EUHOL', "name": 'Euro Yatırım', "category": 'BIST100' },
    { "symbol": 'EUKYO', "name": 'Euro Kapital Yatırım Ortaklığı', "category": 'BIST100' },
    { "symbol": 'EUPWR', "name": 'Europower Enerji', "category": 'BIST100' },
    { "symbol": 'EUREN', "name": 'Europen Endüstri', "category": 'BIST100' },
    { "symbol": 'EUYO', "name": 'Euro Menkul', "category": 'BIST100' },
    { "symbol": 'EYGYO', "name": 'EYG Gayrimenkul', "category": 'BIST100' },
    { "symbol": 'FADE', "name": 'Fade Gıda Yatırım', "category": 'BIST100' },
    { "symbol": 'FENER', "name": 'Fenerbahçe Futbol A.Ş', "category": 'BIST100' },
    { "symbol": 'FLAP', "name": 'Flap Kongre Hiz.Oto.Tur.A.Ş', "category": 'BIST100' },
    { "symbol": 'FMIZP', "name": 'F-M İzmir Piston', "category": 'BIST100' },
    { "symbol": 'FONET', "name": 'Fonet Bilgi Teknolojileri', "category": 'BIST100' },
    { "symbol": 'FORMT', "name": 'Formet Metal ve Cam Sanayii', "category": 'BIST100' },
    { "symbol": 'FORTE', "name": 'Forte Bilgi İletişim', "category": 'BIST100' },
    { "symbol": 'FRIGO', "name": 'Frigo Pak Gıda', "category": 'BIST100' },
    { "symbol": 'FROTO', "name": 'Ford Otosan', "category": 'BIST100' },
    { "symbol": 'FZLGY', "name": 'Fuzul Gayrimenkul', "category": 'BIST100' },
    { "symbol": 'GARAN', "name": 'Garanti Bankası', "category": 'BIST100' },
    { "symbol": 'GARFA', "name": 'Garanti BBVA Faktoring', "category": 'BIST100' },
    { "symbol": 'GEDIK', "name": 'Gedik Yatırım', "category": 'BIST100' },
    { "symbol": 'GEDZA', "name": 'Gediz Ambalaj Sanayi', "category": 'BIST100' },
    { "symbol": 'GENIL', "name": 'Gen İlaç', "category": 'BIST100' },
    { "symbol": 'GENTS', "name": 'Gentaş', "category": 'BIST100' },
    { "symbol": 'GEREL', "name": 'Gersan Elektrik', "category": 'BIST100' },
    { "symbol": 'GESAN', "name": 'Girişim Elektrik', "category": 'BIST100' },
    { "symbol": 'GIPTA', "name": 'Gıpta', "category": 'BIST100' },
    { "symbol": 'GLBMD', "name": 'Global Menkul Değerler', "category": 'BIST100' },
    { "symbol": 'GLCVY', "name": 'Gelecek Varlık Yön.', "category": 'BIST100' },
    { "symbol": 'GLRMK', "name": 'Gülermak Ağır Sanayi', "category": 'BIST100' },
    { "symbol": 'GLRYH', "name": 'Güler Yatırım Holding', "category": 'BIST100' },
    { "symbol": 'GLYHO', "name": 'Global Yatırım Holding', "category": 'BIST100' },
    { "symbol": 'GMTAS', "name": 'Gimat Mağazacılık', "category": 'BIST100' },
    { "symbol": 'GOKNR', "name": 'Göknur Gıda', "category": 'BIST100' },
    { "symbol": 'GOLTS', "name": 'Göltaş Çimento', "category": 'BIST100' },
    { "symbol": 'GOODY', "name": 'Goodyear', "category": 'BIST100' },
    { "symbol": 'GOZDE', "name": 'Gözde Girişim Sermayesi', "category": 'BIST100' },
    { "symbol": 'GRNYO', "name": 'Garanti YO', "category": 'BIST100' },
    { "symbol": 'GRSEL', "name": 'Gürsel Taşımacılık', "category": 'BIST100' },
    { "symbol": 'GRTHO', "name": 'GrainTurk Tarım', "category": 'BIST100' },
    { "symbol": 'GSDDE', "name": 'GSD Denizcilik Gayrimenkul İnş', "category": 'BIST100' },
    { "symbol": 'GSDHO', "name": 'GSD Holding A.Ş', "category": 'BIST100' },
    { "symbol": 'GSRAY', "name": 'Galatasaray Sportif A.Ş', "category": 'BIST100' },
    { "symbol": 'GUBRF', "name": 'Gübre Fabrikaları', "category": 'BIST100' },
    { "symbol": 'GUNDG', "name": 'Gündoğdu Gıda', "category": 'BIST100' },
    { "symbol": 'GWIND', "name": 'Galata Wind Enerji', "category": 'BIST100' },
    { "symbol": 'GZNMI', "name": 'Gezinomi Seyahat', "category": 'BIST100' },
    { "symbol": 'HALKB', "name": 'Halkbank', "category": 'BIST100' },
    { "symbol": 'HATEK', "name": 'Hateks Hatay Tekstil', "category": 'BIST100' },
    { "symbol": 'HATSN', "name": 'Hat-San', "category": 'BIST100' },
    { "symbol": 'HDFGS', "name": 'Hedef Girişim Sermayesi', "category": 'BIST100' },
    { "symbol": 'HEDEF', "name": 'Hedef Holding', "category": 'BIST100' },
    { "symbol": 'HEKTS', "name": 'Hektaş', "category": 'BIST100' },
    { "symbol": 'HKTM', "name": 'Hidropar', "category": 'BIST100' },
    { "symbol": 'HLGYO', "name": 'Halk GYO', "category": 'BIST100' },
    { "symbol": 'HOROZ', "name": 'Horoz Lojistik', "category": 'BIST100' },
    { "symbol": 'HRKET', "name": 'Hareket Proje', "category": 'BIST100' },
    { "symbol": 'HTTBT', "name": 'Hitit Bilgisayar', "category": 'BIST100' },
    { "symbol": 'HUBVC', "name": 'Hub Girişim Ser. Y.O', "category": 'BIST100' },
    { "symbol": 'HUNER', "name": 'Hun Enerji', "category": 'BIST100' },
    { "symbol": 'HURGZ', "name": 'Hürriyet', "category": 'BIST100' },
    { "symbol": 'ICBCT', "name": 'ICBC Turkey Bank', "category": 'BIST100' },
    { "symbol": 'ICUGS', "name": 'Icu Girişim Ser. Y.O', "category": 'BIST100' },
    { "symbol": 'IDGYO', "name": 'İdealist GYO', "category": 'BIST100' },
    { "symbol": 'IEYHO', "name": 'Işıklar Enerji ve Yapı Holding', "category": 'BIST100' },
    { "symbol": 'IHAAS', "name": 'İhlas Haber Ajansı', "category": 'BIST100' },
    { "symbol": 'IHEVA', "name": 'İhlas Ev Aletleri', "category": 'BIST100' },
    { "symbol": 'IHGZT', "name": 'İhlas Gazetecilik', "category": 'BIST100' },
    { "symbol": 'IHLAS', "name": 'İhlas Holding', "category": 'BIST100' },
    { "symbol": 'IHLGM', "name": 'İhlas Gayrimenkul', "category": 'BIST100' },
    { "symbol": 'IHYAY', "name": 'İhlas Yayın Holding', "category": 'BIST100' },
    { "symbol": 'IMASM', "name": 'İmaş Makine', "category": 'BIST100' },
    { "symbol": 'INDES', "name": 'İndeks Bilgisayar', "category": 'BIST100' },
    { "symbol": 'INFO', "name": 'İnfo Yatırım', "category": 'BIST100' },
    { "symbol": 'INGRM', "name": 'İngram Bilişim', "category": 'BIST100' },
    { "symbol": 'INTEK', "name": 'Innosa Teknoloji', "category": 'BIST100' },
    { "symbol": 'INTEM', "name": 'İntema', "category": 'BIST100' },
    { "symbol": 'INVEO', "name": 'İnveo Yatırım Holding', "category": 'BIST100' },
    { "symbol": 'IPEKE', "name": 'İpek Enerji', "category": 'BIST100' },
    { "symbol": 'ISATR', "name": 'İş Bankası (A)', "category": 'BIST100' },
    { "symbol": 'ISBIR', "name": 'İşbir Holding', "category": 'BIST100' },
    { "symbol": 'ISBTR', "name": 'İş Bankası (B)', "category": 'BIST100' },
    { "symbol": 'ISCTR', "name": 'İş Bankası (C)', "category": 'BIST100' },
    { "symbol": 'ISDMR', "name": 'İskenderun Demir Çelik', "category": 'BIST100' },
    { "symbol": 'ISFIN', "name": 'İş Finansal Kiralama', "category": 'BIST100' },
    { "symbol": 'ISGSY', "name": 'İş Girişim', "category": 'BIST100' },
    { "symbol": 'ISGYO', "name": 'İş GYO', "category": 'BIST100' },
    { "symbol": 'ISKPL', "name": 'Işıklar Plastik', "category": 'BIST100' },
    { "symbol": 'ISKUR', "name": 'İş Bankası Kurucu', "category": 'BIST100' },
    { "symbol": 'ISMEN', "name": 'İş Yatırım', "category": 'BIST100' },
    { "symbol": 'ISSEN', "name": 'İşbir Sentetik', "category": 'BIST100' },
    { "symbol": 'ISYAT', "name": 'İs YO', "category": 'BIST100' },
    { "symbol": 'IZENR', "name": 'İzdemir Enerji', "category": 'BIST100' },
    { "symbol": 'IZFAS', "name": 'İzmir Fırça', "category": 'BIST100' },
    { "symbol": 'IZINV', "name": 'İz Yatırım Holding', "category": 'BIST100' },
    { "symbol": 'IZMDC', "name": 'İzmir Demir Çelik', "category": 'BIST100' },
    { "symbol": 'JANTS', "name": 'Jantsa Jant', "category": 'BIST100' },
    { "symbol": 'KAPLM', "name": 'Kaplamin', "category": 'BIST100' },
    { "symbol": 'KAREL', "name": 'Karel Elektronik', "category": 'BIST100' },
    { "symbol": 'KARSN', "name": 'Karsan Otomativ', "category": 'BIST100' },
    { "symbol": 'KARTN', "name": 'Kartonsan', "category": 'BIST100' },
    { "symbol": 'KARYE', "name": 'Kartal Yenilenebilir Enerji', "category": 'BIST100' },
    { "symbol": 'KATMR', "name": 'Katmerciler Araç Üstü Ekipman', "category": 'BIST100' },
    { "symbol": 'KAYSE', "name": 'Kayseri Şeker', "category": 'BIST100' },
    { "symbol": 'KBORU', "name": 'Kuzey Boru', "category": 'BIST100' },
    { "symbol": 'KCAER', "name": 'Kocaer Çelik Sanayi', "category": 'BIST100' },
    { "symbol": 'KCHOL', "name": 'Koç Holding', "category": 'BIST100' },
    { "symbol": 'KENT', "name": 'Kent Gıda', "category": 'BIST100' },
    { "symbol": 'KERVN', "name": 'Kervansaray Yat. Holding', "category": 'BIST100' },
    { "symbol": 'KERVT', "name": 'Kerevitaş', "category": 'BIST100' },
    { "symbol": 'KFEIN', "name": 'Kafein Yazılım', "category": 'BIST100' },
    { "symbol": 'KGYO', "name": 'Koray GYO', "category": 'BIST100' },
    { "symbol": 'KIMMR', "name": 'Ersan Alışveriş Hizmetleri', "category": 'BIST100' },
    { "symbol": 'KLGYO', "name": 'Kiler GYO', "category": 'BIST100' },
    { "symbol": 'KLKIM', "name": 'Kalekim Kimyevi Maddeler', "category": 'BIST100' },
    { "symbol": 'KLMSN', "name": 'Klimasan', "category": 'BIST100' },
    { "symbol": 'KLNMA', "name": 'T. Kalkınma Bankası', "category": 'BIST100' },
    { "symbol": 'KLRHO', "name": 'Kiler Holding', "category": 'BIST100' },
    { "symbol": 'KLSER', "name": 'Kaleseramik', "category": 'BIST100' },
    { "symbol": 'KLSYN', "name": 'Koleksiyon Mobilya', "category": 'BIST100' },
    { "symbol": 'KLYPV', "name": 'Kalyon Güneş Teknolojileri', "category": 'BIST100' },
    { "symbol": 'KMPUR', "name": 'Kimteks Poliüretan', "category": 'BIST100' },
    { "symbol": 'KNFRT', "name": 'Konfrut Gıda', "category": 'BIST100' },
    { "symbol": 'KOCMT', "name": 'Koç Metalurji', "category": 'BIST100' },
    { "symbol": 'KONKA', "name": 'Konya Kağıt', "category": 'BIST100' },
    { "symbol": 'KONTR', "name": 'Kontrolmatik Teknoloji', "category": 'BIST100' },
    { "symbol": 'KONYA', "name": 'Konya Çimento', "category": 'BIST100' },
    { "symbol": 'KOPOL', "name": 'Koza Polyester', "category": 'BIST100' },
    { "symbol": 'KORDS', "name": 'Kordsa Teknik Tekstil', "category": 'BIST100' },
    { "symbol": 'KOTON', "name": 'Koton', "category": 'BIST100' },
    { "symbol": 'KOZAA', "name": 'Koza Anadolu Metal', "category": 'BIST100' },
    { "symbol": 'KOZAL', "name": 'Koza Altın', "category": 'BIST100' },
    { "symbol": 'KRDMA', "name": 'Kardemir (A)', "category": 'BIST100' },
    { "symbol": 'KRDMB', "name": 'Kardemir (B)', "category": 'BIST100' },
    { "symbol": 'KRDMD', "name": 'Kardemir (D)', "category": 'BIST100' },
    { "symbol": 'KRGYO', "name": 'Korfez GYO', "category": 'BIST100' },
    { "symbol": 'KRONT', "name": 'Kron Telekomünikasyon', "category": 'BIST100' },
    { "symbol": 'KRPLS', "name": 'Koroplast Temizlik Ambalaj', "category": 'BIST100' },
    { "symbol": 'KRSTL', "name": 'Kristal Kola', "category": 'BIST100' },
    { "symbol": 'KRTEK', "name": 'Karsu Tekstil', "category": 'BIST100' },
    { "symbol": 'KRVGD', "name": 'Kervan Gıda', "category": 'BIST100' },
    { "symbol": 'KSTUR', "name": 'Kuştur Turizm', "category": 'BIST100' },
    { "symbol": 'KTLEV', "name": 'Katılımevim', "category": 'BIST100' },
    { "symbol": 'KTSKR', "name": 'Kütahya Şeker', "category": 'BIST100' },
    { "symbol": 'KUTPO', "name": 'Kütahya Porselen', "category": 'BIST100' },
    { "symbol": 'KUVVA', "name": 'Kuvva Gıda', "category": 'BIST100' },
    { "symbol": 'KUYAS', "name": 'Kuyas Yatırım A.Ş', "category": 'BIST100' },
    { "symbol": 'KZBGY', "name": 'Kızılbük GYO', "category": 'BIST100' },
    { "symbol": 'KZGYO', "name": 'Kuzugrup GYO', "category": 'BIST100' },
    { "symbol": 'LIDER', "name": 'Lider Turizm', "category": 'BIST100' },
    { "symbol": 'LIDFA', "name": 'Lider Faktoring', "category": 'BIST100' },
    { "symbol": 'LILAK', "name": 'Lila Kağıt', "category": 'BIST100' },
    { "symbol": 'LINK', "name": 'Link Bilgisayar', "category": 'BIST100' },
    { "symbol": 'LKMNH', "name": 'Lokman Hekim Engurusag', "category": 'BIST100' },
    { "symbol": 'LMKDC', "name": 'Limak Doğu Anadolu Çimento', "category": 'BIST100' },
    { "symbol": 'LOGO', "name": 'Logo Yazılım', "category": 'BIST100' },
    { "symbol": 'LRSHO', "name": 'Loras Holding', "category": 'BIST100' },
    { "symbol": 'LUKSK', "name": 'Lüks Kadife', "category": 'BIST100' },
    { "symbol": 'LYDHO', "name": 'Lydia Holding', "category": 'BIST100' },
    { "symbol": 'LYDYE', "name": 'Tetamat Gıda', "category": 'BIST100' },
    { "symbol": 'MAALT', "name": 'Marmaris Altınyunus', "category": 'BIST100' },
    { "symbol": 'MACKO', "name": 'Maçkolik', "category": 'BIST100' },
    { "symbol": 'MAGEN', "name": 'Margün Enerji', "category": 'BIST100' },
    { "symbol": 'MAKIM', "name": 'Makim Makina', "category": 'BIST100' },
    { "symbol": 'MAKTK', "name": 'Makina Takım', "category": 'BIST100' },
    { "symbol": 'MANAS', "name": 'Manas Enerji Yönetimi', "category": 'BIST100' },
    { "symbol": 'MARBL', "name": 'Tureks Turunç', "category": 'BIST100' },
    { "symbol": 'MARKA', "name": 'Marka Yatırım Holding', "category": 'BIST100' },
    { "symbol": 'MARTI', "name": 'Martı Otel İşletmeleri', "category": 'BIST100' },
    { "symbol": 'MAVI', "name": 'Mavi Giyim Sanayi Tic.A.Ş', "category": 'BIST100' },
    { "symbol": 'MEDTR', "name": 'Meditera Tıbbi Malzeme', "category": 'BIST100' },
    { "symbol": 'MEGAP', "name": 'Mega Polietilen Köpük', "category": 'BIST100' },
    { "symbol": 'MEGMT', "name": 'Mega Metal', "category": 'BIST100' },
    { "symbol": 'MEKAG', "name": 'Meka Beton', "category": 'BIST100' },
    { "symbol": 'MEPET', "name": 'Metro Petrol ve Tesisleri', "category": 'BIST100' },
    { "symbol": 'MERIT', "name": 'Merit Turizm Yatırım', "category": 'BIST100' },
    { "symbol": 'MERKO', "name": 'Merko Gıda', "category": 'BIST100' },
    { "symbol": 'METRO', "name": 'Metro Tic. Mali Yat.', "category": 'BIST100' },
    { "symbol": 'METUR', "name": 'Matemtur Yatırım Tur.Enj.', "category": 'BIST100' },
    { "symbol": 'MGROS', "name": 'Migros', "category": 'BIST100' },
    { "symbol": 'MHRGY', "name": 'Mhr GYO', "category": 'BIST100' },
    { "symbol": 'MIATK', "name": 'Mia Teknoloji', "category": 'BIST100' },
    { "symbol": 'MMCAS', "name": 'MMC San. ve Tic. Yatırımlar A.Ş', "category": 'BIST100' },
    { "symbol": 'MNDRS', "name": 'Menderes Tekstil', "category": 'BIST100' },
    { "symbol": 'MNDTR', "name": 'Mondi Tire', "category": 'BIST100' },
    { "symbol": 'MOBTL', "name": 'Mobitel İletişim', "category": 'BIST100' },
    { "symbol": 'MOGAN', "name": 'Mogan Enerji', "category": 'BIST100' },
    { "symbol": 'MOPAS', "name": 'Mopaş', "category": 'BIST100' },
    { "symbol": 'MPARK', "name": 'MLP Sağlık Hizmetleri', "category": 'BIST100' },
    { "symbol": 'MRGYO', "name": 'Martı GYO', "category": 'BIST100' },
    { "symbol": 'MRSHL', "name": 'Marshall', "category": 'BIST100' },
    { "symbol": 'MSGYO', "name": 'Mistral GYO', "category": 'BIST100' },
    { "symbol": 'MTRKS', "name": 'Matriks Bilgi Dağıtım', "category": 'BIST100' },
    { "symbol": 'MTRYO', "name": 'Metro YO', "category": 'BIST100' },
    { "symbol": 'MZHLD', "name": 'Mazhar Zorlu Holding', "category": 'BIST100' },
    { "symbol": 'NATEN', "name": 'Natural Yenilenebilir Enerji', "category": 'BIST100' },
    { "symbol": 'NETAS', "name": 'Netaş', "category": 'BIST100' },
    { "symbol": 'NIBAS', "name": 'Niğde Beton Sanayi', "category": 'BIST100' },
    { "symbol": 'NTGAZ', "name": 'Naturel Gaz', "category": 'BIST100' },
    { "symbol": 'NTHOL', "name": 'Net Holding', "category": 'BIST100' },
    { "symbol": 'NUGYO', "name": 'Nurol GYO', "category": 'BIST100' },
    { "symbol": 'NUHCM', "name": 'Nuh Çimento', "category": 'BIST100' },
    { "symbol": 'OBAMS', "name": 'Oba Makarnacılık', "category": 'BIST100' },
    { "symbol": 'OBASE', "name": 'Obase Bilgisayar Danışmanlık', "category": 'BIST100' },
    { "symbol": 'ODAS', "name": 'Odaş Elektrik Üretim', "category": 'BIST100' },
    { "symbol": 'ODINE', "name": 'Odine Solutions', "category": 'BIST100' },
    { "symbol": 'OFSYM', "name": 'Ofis Yem', "category": 'BIST100' },
    { "symbol": 'ONCSM', "name": 'Oncosem', "category": 'BIST100' },
    { "symbol": 'ONRYT', "name": 'Onur Yüksek Teknoloji', "category": 'BIST100' },
    { "symbol": 'ORCAY', "name": 'Ortaköy Çay Sanayi', "category": 'BIST100' },
    { "symbol": 'ORGE', "name": 'ORGE Enerji Elektrik', "category": 'BIST100' },
    { "symbol": 'ORMA', "name": 'Orma Orman Mahsulleri', "category": 'BIST100' },
    { "symbol": 'OSMEN', "name": 'Osmanlı Menkul Değ.', "category": 'BIST100' },
    { "symbol": 'OSTIM', "name": 'Ostim Endüst. Yatırımlar', "category": 'BIST100' },
    { "symbol": 'OTKAR', "name": 'Otokar', "category": 'BIST100' },
    { "symbol": 'OTTO', "name": 'Otto Holding', "category": 'BIST100' },
    { "symbol": 'OYAKC', "name": 'Oyak Çimento', "category": 'BIST100' },
    { "symbol": 'OYAYO', "name": 'Oyak Yatırım Ortaklığı', "category": 'BIST100' },
    { "symbol": 'OYLUM', "name": 'Oylum Sınai Yatırımlar', "category": 'BIST100' },
    { "symbol": 'OYYAT', "name": 'Oyak Yatırım', "category": 'BIST100' },
    { "symbol": 'OZATD', "name": 'Özata Denizcilik', "category": 'BIST100' },
    { "symbol": 'OZGYO', "name": 'Özderici GYO', "category": 'BIST100' },
    { "symbol": 'OZKGY', "name": 'Özak GYO', "category": 'BIST100' },
    { "symbol": 'OZRDN', "name": 'Özerden Plastik', "category": 'BIST100' },
    { "symbol": 'OZSUB', "name": 'Özsu Balık', "category": 'BIST100' },
    { "symbol": 'OZYSR', "name": 'Özyaşar Tel', "category": 'BIST100' },
    { "symbol": 'PAGYO', "name": 'Panora GYO', "category": 'BIST100' },
    { "symbol": 'PAMEL', "name": 'Pamel Yenilenebilir Elekt.', "category": 'BIST100' },
    { "symbol": 'PAPIL', "name": 'Papilon Savunma', "category": 'BIST100' },
    { "symbol": 'PARSN', "name": 'Parsan', "category": 'BIST100' },
    { "symbol": 'PASEU', "name": 'Pasifik Eurasia', "category": 'BIST100' },
    { "symbol": 'PATEK', "name": 'Pasifik Teknoloji', "category": 'BIST100' },
    { "symbol": 'PCILT', "name": 'PC İletişim ve Medya', "category": 'BIST100' },
    { "symbol": 'PEHOL', "name": 'Pera Holding', "category": 'BIST100' },
    { "symbol": 'PEKGY', "name": 'Peker GYO', "category": 'BIST100' },
    { "symbol": 'PENGD', "name": 'Penguen Gıda', "category": 'BIST100' },
    { "symbol": 'PENTA', "name": 'Penta Teknoloji', "category": 'BIST100' },
    { "symbol": 'PETKM', "name": 'Petkim', "category": 'BIST100' },
    { "symbol": 'PETUN', "name": 'Pınar Et ve Un', "category": 'BIST100' },
    { "symbol": 'PGSUS', "name": 'Pegasus Hava Taşımacılığı', "category": 'BIST100' },
    { "symbol": 'PINSU', "name": 'Pınar Su', "category": 'BIST100' },
    { "symbol": 'PKART', "name": 'Plastikkart A.Ş', "category": 'BIST100' },
    { "symbol": 'PKENT', "name": 'Petrokent', "category": 'BIST100' },
    { "symbol": 'PLTUR', "name": 'Platform Turizm', "category": 'BIST100' },
    { "symbol": 'PNLSN', "name": 'Panelsan Çatı Cephe', "category": 'BIST100' },
    { "symbol": 'PNSUT', "name": 'Pınar Süt', "category": 'BIST100' },
    { "symbol": 'POLHO', "name": 'Polisan Holding', "category": 'BIST100' },
    { "symbol": 'POLTK', "name": 'Politeknik Metal', "category": 'BIST100' },
    { "symbol": 'PRDGS', "name": 'Pardus Girişim', "category": 'BIST100' },
    { "symbol": 'PRKAB', "name": 'Prysmian Kablo', "category": 'BIST100' },
    { "symbol": 'PRKME', "name": 'Park Elek. Madencilik', "category": 'BIST100' },
    { "symbol": 'PRZMA', "name": 'Prizma Pres Matbaacılık', "category": 'BIST100' },
    { "symbol": 'PSDTC', "name": 'Pergamon Status', "category": 'BIST100' },
    { "symbol": 'PSGYO', "name": 'Pasifik GYO', "category": 'BIST100' },
    { "symbol": 'QNBFK', "name": 'QNB Finans Fin. Kir.', "category": 'BIST100' },
    { "symbol": 'QNBTR', "name": 'QNB Bank', "category": 'BIST100' },
    { "symbol": 'QUAGR', "name": 'QUA Granite', "category": 'BIST100' },
    { "symbol": 'RALYH', "name": 'Ral Yatırım Holding', "category": 'BIST100' },
    { "symbol": 'RAYSG', "name": 'Ray Sigorta', "category": 'BIST100' },
    { "symbol": 'REEDR', "name": 'Reeder', "category": 'BIST100' },
    { "symbol": 'RGYAS', "name": 'Rönesans Gayrimenkul', "category": 'BIST100' },
    { "symbol": 'RNPOL', "name": 'Rainbow Polikarbonat', "category": 'BIST100' },
    { "symbol": 'RODRG', "name": 'Rodrigo Tekstil', "category": 'BIST100' },
    { "symbol": 'ROYAL', "name": 'Royal Halı', "category": 'BIST100' },
    { "symbol": 'RTALB', "name": 'RTA Labaratuvarları', "category": 'BIST100' },
    { "symbol": 'RUBNS', "name": 'Rubenis Tekstil', "category": 'BIST100' },
    { "symbol": 'RYGYO', "name": 'Reysaş GYO', "category": 'BIST100' },
    { "symbol": 'RYSAS', "name": 'Reysaş Taşımacılık', "category": 'BIST100' },
    { "symbol": 'SAFKR', "name": 'Safkar Ege Soğutmacılık', "category": 'BIST100' },
    { "symbol": 'SAHOL', "name": 'Sabancı Holding', "category": 'BIST100' },
    { "symbol": 'SAMAT', "name": 'Saray Matbaacılık', "category": 'BIST100' },
    { "symbol": 'SANEL', "name": 'San-El Mühendislik', "category": 'BIST100' },
    { "symbol": 'SANFM', "name": 'Sanifoam Sünger Sanayi', "category": 'BIST100' },
    { "symbol": 'SANKO', "name": 'Sanko Pazarlama', "category": 'BIST100' },
    { "symbol": 'SARKY', "name": 'Sarkuysan', "category": 'BIST100' },
    { "symbol": 'SASA', "name": 'Sasa Polyester Sanayi A.Ş', "category": 'BIST100' },
    { "symbol": 'SAYAS', "name": 'Say Yenilenebilir Enerji', "category": 'BIST100' },
    { "symbol": 'SDTTR', "name": 'SDT Uzay', "category": 'BIST100' },
    { "symbol": 'SEGMN', "name": 'Seğmen Gıda', "category": 'BIST100' },
    { "symbol": 'SEGYO', "name": 'Şeker GYO', "category": 'BIST100' },
    { "symbol": 'SEKFK', "name": 'Şeker Finansal Kiralama A.Ş', "category": 'BIST100' },
    { "symbol": 'SEKUR', "name": 'Sekuro Plastik', "category": 'BIST100' },
    { "symbol": 'SELEC', "name": 'Selçuk Ecza Deposu', "category": 'BIST100' },
    { "symbol": 'SELGD', "name": 'Selçuk Gıda', "category": 'BIST100' },
    { "symbol": 'SELVA', "name": 'Selva Gıda', "category": 'BIST100' },
    { "symbol": 'SERNT', "name": 'Seranit Granit', "category": 'BIST100' },
    { "symbol": 'SEYKM', "name": 'Seyitler Kimya', "category": 'BIST100' },
    { "symbol": 'SILVR', "name": 'Silverline', "category": 'BIST100' },
    { "symbol": 'SISE', "name": 'Şişecam', "category": 'BIST100' },
    { "symbol": 'SKBNK', "name": 'Şekerbank', "category": 'BIST100' },
    { "symbol": 'SKTAS', "name": 'Söktaş', "category": 'BIST100' },
    { "symbol": 'SKYLP', "name": 'Skyalp Fin. Tek. ve Danışmanlık', "category": 'BIST100' },
    { "symbol": 'SKYMD', "name": 'Şeker Yatırım', "category": 'BIST100' },
    { "symbol": 'SMART', "name": 'Smartiks Yazılım', "category": 'BIST100' },
    { "symbol": 'SMRTG', "name": 'Smart Güneş Enerjisi', "category": 'BIST100' },
    { "symbol": 'SMRVA', "name": 'Sümer Varlık Yönetim', "category": 'BIST100' },
    { "symbol": 'SNGYO', "name": 'Sinpas GYO', "category": 'BIST100' },
    { "symbol": 'SNICA', "name": 'Sanica Isı Sanayi', "category": 'BIST100' },
    { "symbol": 'SNKRN', "name": 'Senkron Güvenlik', "category": 'BIST100' },
    { "symbol": 'SNPAM', "name": 'Sönmez Pamuklu', "category": 'BIST100' },
    { "symbol": 'SODSN', "name": 'Sodaş Sodyum Sanayii', "category": 'BIST100' },
    { "symbol": 'SOKE', "name": 'Söke Değirmencilik', "category": 'BIST100' },
    { "symbol": 'SOKM', "name": 'Şok Marketler', "category": 'BIST100' },
    { "symbol": 'SONME', "name": 'Sönmez Filament', "category": 'BIST100' },
    { "symbol": 'SRVGY', "name": 'Servet GYO', "category": 'BIST100' },
    { "symbol": 'SUMAS', "name": 'Sumas Mobilya', "category": 'BIST100' },
    { "symbol": 'SUNTK', "name": 'Sun Tekstil', "category": 'BIST100' },
    { "symbol": 'SURGY', "name": 'Sur GYO', "category": 'BIST100' },
    { "symbol": 'SUWEN', "name": 'Suwen Tekstil', "category": 'BIST100' },
    { "symbol": 'TABGD', "name": 'Tab Gıda', "category": 'BIST100' },
    { "symbol": 'TARKM', "name": 'Tarkim', "category": 'BIST100' },
    { "symbol": 'TATEN', "name": 'Tatlıpınar Enerji', "category": 'BIST100' },
    { "symbol": 'TATGD', "name": 'Tat Gıda', "category": 'BIST100' },
    { "symbol": 'TAVHL', "name": 'TAV Holding', "category": 'BIST100' },
    { "symbol": 'TBORG', "name": 'Tuborg', "category": 'BIST100' },
    { "symbol": 'TCELL', "name": 'Turkcell', "category": 'BIST100' },
    { "symbol": 'TCKRC', "name": 'Kıraç Galvaniz', "category": 'BIST100' },
    { "symbol": 'TDGYO', "name": 'Trend GYO', "category": 'BIST100' },
    { "symbol": 'TEKTU', "name": 'Tek-Art Turizm', "category": 'BIST100' },
    { "symbol": 'TERA', "name": 'Tera Yatırım', "category": 'BIST100' },
    { "symbol": 'TEZOL', "name": 'Europap Tezol', "category": 'BIST100' },
    { "symbol": 'TGSAS', "name": 'TGS Dış Ticaret', "category": 'BIST100' },
    { "symbol": 'THYAO', "name": 'Türk Hava Yolları', "category": 'BIST100' },
    { "symbol": 'TKFEN', "name": 'Tekfen Holding', "category": 'BIST100' },
    { "symbol": 'TKNSA', "name": 'Teknosa İç ve Dış Tic.', "category": 'BIST100' },
    { "symbol": 'TLMAN', "name": 'Trabzon Liman İşletmeciliği', "category": 'BIST100' },
    { "symbol": 'TMPOL', "name": 'TE-MAPOL Polimer Plastik', "category": 'BIST100' },
    { "symbol": 'TMSN', "name": 'Tümosan Motor ve Traktör', "category": 'BIST100' },
    { "symbol": 'TNZTP', "name": 'Tapdi Oksijen', "category": 'BIST100' },
    { "symbol": 'TOASO', "name": 'Tofaş Fabrika', "category": 'BIST100' },
    { "symbol": 'TRCAS', "name": 'Turcas', "category": 'BIST100' },
    { "symbol": 'TRGYO', "name": 'Torunlar GYO', "category": 'BIST100' },
    { "symbol": 'TRILC', "name": 'Türk İlaç ve Serum Sanayi', "category": 'BIST100' },
    { "symbol": 'TSGYO', "name": 'TSKB GYO', "category": 'BIST100' },
    { "symbol": 'TSKB', "name": 'TSKB', "category": 'BIST100' },
    { "symbol": 'TSPOR', "name": 'Trabzonsport A.Ş', "category": 'BIST100' },
    { "symbol": 'TTKOM', "name": 'Türk Telekom', "category": 'BIST100' },
    { "symbol": 'TTRAK', "name": 'Türk Traktör', "category": 'BIST100' },
    { "symbol": 'TUCLK', "name": 'Tuğçelik Alüminyum ve Metal', "category": 'BIST100' },
    { "symbol": 'TUKAS', "name": 'Tukaş', "category": 'BIST100' },
    { "symbol": 'TUPRS', "name": 'Tüpraş', "category": 'BIST100' },
    { "symbol": 'TUREX', "name": 'Tureks Tur. Taşımacılık', "category": 'BIST100' },
    { "symbol": 'TURGG', "name": 'Türker Proje Gay. Gel.', "category": 'BIST100' },
    { "symbol": 'TURSG', "name": 'Türkiye Sigorta', "category": 'BIST100' },
    { "symbol": 'UFUK', "name": 'Ufuk Yat. Yön. ve Gay. A.Ş', "category": 'BIST100' },
    { "symbol": 'ULAS', "name": 'Ulaşlar Turizm Yatırımları', "category": 'BIST100' },
    { "symbol": 'ULKER', "name": 'Ülker Bisküvi', "category": 'BIST100' },
    { "symbol": 'ULUFA', "name": 'Ulusal Faktoring', "category": 'BIST100' },
    { "symbol": 'ULUSE', "name": 'Ulusoy Elektrik', "category": 'BIST100' },
    { "symbol": 'ULUUN', "name": 'Ulusoy Un', "category": 'BIST100' },
    { "symbol": 'UMPAS', "name": 'Umpaş Holding', "category": 'BIST100' },
    { "symbol": 'UNLU', "name": 'Ünlü Yatırım Holding', "category": 'BIST100' },
    { "symbol": 'USAK', "name": 'Uşak Seramik', "category": 'BIST100' },
    { "symbol": 'VAKBN', "name": 'Vakıfbank', "category": 'BIST100' },
    { "symbol": 'VAKFN', "name": 'Vakıf Fin. Kir.', "category": 'BIST100' },
    { "symbol": 'VAKKO', "name": 'Vakko Tekstil', "category": 'BIST100' },
    { "symbol": 'VANGD', "name": 'Vanet Gıda Sanayi', "category": 'BIST100' },
    { "symbol": 'VBTYZ', "name": 'VBT Yazılım', "category": 'BIST100' },
    { "symbol": 'VERTU', "name": 'Verusatürk Girişim Sermayesi', "category": 'BIST100' },
    { "symbol": 'VERUS', "name": 'Verusa Holding', "category": 'BIST100' },
    { "symbol": 'VESBE', "name": 'Vestel Beyaz Eşya', "category": 'BIST100' },
    { "symbol": 'VESTL', "name": 'Vestel Elektronik', "category": 'BIST100' },
    { "symbol": 'VKFYO', "name": 'Vakıf YO', "category": 'BIST100' },
    { "symbol": 'VKGYO', "name": 'Vakıf GYO', "category": 'BIST100' },
    { "symbol": 'VKING', "name": 'Viking Kağıt', "category": 'BIST100' },
    { "symbol": 'VRGYO', "name": 'Vera GYO', "category": 'BIST100' },
    { "symbol": 'VSNMD', "name": 'Vişne Madencilik', "category": 'BIST100' },
    { "symbol": 'YAPRK', "name": 'Yaprak Süt & Besi Çiftlikleri', "category": 'BIST100' },
    { "symbol": 'YATAS', "name": 'Yataş Yatak', "category": 'BIST100' },
    { "symbol": 'YAYLA', "name": 'Yayla Enerji Üterim Turizm', "category": 'BIST100' },
    { "symbol": 'YBTAS', "name": 'Yibitaş İnş. Malzemeleri', "category": 'BIST100' },
    { "symbol": 'YEOTK', "name": 'YEO Teknoloji', "category": 'BIST100' },
    { "symbol": 'YESIL', "name": 'Yeşil Yatırım Holding', "category": 'BIST100' },
    { "symbol": 'YGGYO', "name": 'Yeni Gimay GYO', "category": 'BIST100' },
    { "symbol": 'YGYO', "name": 'Yeşil GYO', "category": 'BIST100' },
    { "symbol": 'YIGIT', "name": 'Yiğit Akü', "category": 'BIST100' },
    { "symbol": 'YKBNK', "name": 'Yapı Kredi Bankası', "category": 'BIST100' },
    { "symbol": 'YKSLN', "name": 'Yükselen Çelik', "category": 'BIST100' },
    { "symbol": 'YONGA', "name": 'Yonga Mobilya Sanayi', "category": 'BIST100' },
    { "symbol": 'YUNSA', "name": 'Yünsa', "category": 'BIST100' },
    { "symbol": 'YYAPI', "name": 'Yeşil Yapı', "category": 'BIST100' },
    { "symbol": 'YYLGD', "name": 'Yayla Agro Gıda', "category": 'BIST100' },
    { "symbol": 'ZEDUR', "name": 'Zedur Enerji', "category": 'BIST100' },
    { "symbol": 'ZOREN', "name": 'Zorlu Enerji', "category": 'BIST100' },
    { "symbol": 'ZRGYO', "name": 'Ziraat GYO', "category": 'BIST100' },
]